(function(root){'use strict';
const VERSION='1.0.1',ENTRY_MODES=['frontend','user','admin'],SAVING_SHEET_ID='1-QG1tnH0iTYLAzweJ6Gvj5JDN5p1YKIq9IONyvVIo4U',MEDICAL_SHEET_ID='1G6JirabWJPrTtsdPuzzfyo-D-EPIbbdCM3HvFUW7ZCw';const savingCache={},medicalCache={};
const cleanNum=value=>parseInt(String(value).replace(/[^\d]/g,''),10)||0;const fmtMoney=value=>new Intl.NumberFormat('en-US',{maximumFractionDigits:0}).format(Math.round(value));
function parseCSV(text){let rows=[],row=[],col='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i],next=text[i+1];if(c==='"'&&quoted&&next==='"'){col+=c;i++;continue}if(c==='"'){quoted=!quoted;continue}if(c===','&&!quoted){row.push(col);col='';continue}if(c==='\r'&&!quoted)continue;if(c==='\n'&&!quoted){row.push(col);rows.push(row);row=[];col='';continue}col+=c}if(col!=='')row.push(col);if(row.length)rows.push(row);return rows}
function parseSavingRows(rows){const parsed=[];for(let i=1;i<rows.length;i++){if(rows[i].length<3)continue;const year=parseInt(rows[i][0].replace(/,/g,''),10),rate=parseFloat(rows[i][1].replace(/,/g,'')),mult=parseFloat(rows[i][2].replace(/,/g,''));if(!Number.isNaN(year)&&!Number.isNaN(rate)&&!Number.isNaN(mult))parsed.push({year,rate,mult})}return parsed}
function parseMedicalRows(rows){const parsed={};for(let i=1;i<rows.length;i++){if(rows[i].length<2)continue;const age=parseInt(rows[i][0].replace(/,/g,''),10),premium=parseFloat(rows[i][1].replace(/[",]/g,''));if(!Number.isNaN(age)&&!Number.isNaN(premium))parsed[age]=premium}return parsed}
function interpolatedMultiplier(data,year){if(!data.length)return 0;if(year<=data[0].year)return data[0].mult*(year/data[0].year);if(year>=data[data.length-1].year)return data[data.length-1].mult;for(let i=0;i<data.length-1;i++){if(year>=data[i].year&&year<=data[i+1].year){const a=data[i],b=data[i+1];return a.mult+(b.mult-a.mult)*((year-a.year)/(b.year-a.year))}}return 0}
function extractionStart(plan){if(plan.includes('1year'))return 1;if(plan.includes('3year'))return 3;if(plan.includes('5year'))return 5;return 999}
function calculateMedical({principal,currentAge,retirementAge,lifeExpectancy,adjustmentRate,plan,savingData,medicalData}){const start=extractionStart(plan),retirementPolicyYear=retirementAge-currentAge,rate=savingData.length?savingData[0].rate:0;let totalPremium=0,totalRelief=0,totalActual=0,finalBalance=0;const rows=[];for(let targetAge=retirementAge;targetAge<=lifeExpectancy;targetAge++){const progressYear=targetAge-retirementAge;let policyYear=retirementPolicyYear+progressYear;if(policyYear<=0)policyYear=1;const base=medicalData[targetAge]||8000;const premium=base*Math.pow(1+adjustmentRate,policyYear);const relief=policyYear>=start?principal*rate:0;const actual=Math.max(0,premium-relief);const balance=principal*interpolatedMultiplier(savingData,policyYear);totalPremium+=premium;totalRelief+=relief;totalActual+=actual;if(targetAge===lifeExpectancy)finalBalance=balance;if(targetAge%5===0||targetAge===retirementAge||targetAge===lifeExpectancy)rows.push({targetAge,progressYear,premium,relief,actual,balance})}return{rows,totalPremium,totalRelief,totalActual,finalBalance,netOutcome:totalRelief+finalBalance-totalActual-principal}}
async function fetchRows(sheetId,tab){const response=await fetch(`https://docs.google.com/spreadsheets/d/${sheetId}/gviz/tq?tqx=out:csv&sheet=${encodeURIComponent(tab)}`);if(!response.ok)throw new Error(`HTTP ${response.status}`);return parseCSV(await response.text())}
async function loadSaving(plan){if(!savingCache[plan])savingCache[plan]=parseSavingRows(await fetchRows(SAVING_SHEET_ID,plan));return savingCache[plan]}async function loadMedical(plan){if(!medicalCache[plan])medicalCache[plan]=parseMedicalRows(await fetchRows(MEDICAL_SHEET_ID,plan));return medicalCache[plan]}
function setStatus(message,error=false){const el=document.getElementById('status');el.textContent=message;el.classList.toggle('is-error',error)}
async function render(){const tbody=document.getElementById('medical-table-body');tbody.innerHTML='';setStatus('正在連線 A+ 儲蓄庫及醫保庫…');try{const plan=document.getElementById('med-saving-plan-select').value,medicalPlan=document.getElementById('med-plan-select').value;const[savingData,medicalData]=await Promise.all([loadSaving(plan),loadMedical(medicalPlan)]);const result=calculateMedical({principal:cleanNum(document.getElementById('med-principal').value)||200000,currentAge:parseInt(document.getElementById('med-age').value,10)||40,retirementAge:parseInt(document.getElementById('med-retirement-age').value,10)||60,lifeExpectancy:parseInt(document.getElementById('med-life-expectancy').value,10)||85,adjustmentRate:parseFloat(document.getElementById('med-adjustment-slider').value)/100,plan,savingData,medicalData});tbody.innerHTML=result.rows.map(row=>`<tr><td><strong>退休第 ${row.progressYear} 年</strong>（${row.targetAge}歲）</td><td>$${fmtMoney(row.premium)}</td><td>${row.relief?'+$'+fmtMoney(row.relief):'$0'}</td><td class="actual-column" hidden>$${fmtMoney(row.actual)}</td><td>$${fmtMoney(row.balance)}</td></tr>`).join('')+`<tr class="total-row"><td>總計累額</td><td>$${fmtMoney(result.totalPremium)}</td><td>$${fmtMoney(result.totalRelief)}</td><td class="actual-column" hidden>$${fmtMoney(result.totalActual)}</td><td>$${fmtMoney(result.finalBalance)}</td></tr>`;document.getElementById('calc-outcome-a').textContent='-$'+fmtMoney(result.totalPremium);document.getElementById('calc-outcome-b').textContent=(result.netOutcome<0?'-$':'$')+fmtMoney(Math.abs(result.netOutcome));setStatus(`已載入 ${result.rows.length} 個退休節點`) }catch(error){console.error(error);setStatus('讀取失敗，請檢查網絡或 Google Sheet 權限。',true);tbody.innerHTML='<tr><td colspan="5">暫時未能載入資料</td></tr>'}}
function setupEntryContext(){const requested=new URLSearchParams(location.search).get('avaEntry');if(!ENTRY_MODES.includes(requested))return;document.body.dataset.avaEntry=requested;const link=document.getElementById('ava-back-link'),panel=document.getElementById('integration-context'),title=document.getElementById('integration-title'),copy=document.getElementById('integration-copy');link.hidden=false;if(requested==='frontend'){link.href='https://ivancww.github.io/avaplatform/';link.textContent='← AVA 首頁';title.textContent='Frontstage';copy.textContent='正式退休醫療保費及儲備計算。'}else if(requested==='user'){link.href='https://ivancww.github.io/avaplatform/?avaSurface=user';link.textContent='← 我的流程';title.textContent='使用者入口';copy.textContent='使用者可按目前情況調整本金、退休年齡、醫療計劃及通脹假設；本 Module 不儲存個人或客戶資料。'}else{link.href='https://ivancww.github.io/avaplatform/?avaSurface=admin';link.textContent='← AVA Studio';title.textContent='管理者入口';copy.textContent=`Integration v${VERSION} · 官方 Saving／Medical Sheet mapping 及 Onetime 計算基準保持唯讀。`}panel.hidden=false}
function setup(){setupEntryContext();const principal=document.getElementById('med-principal');principal.addEventListener('input',()=>{const value=cleanNum(principal.value);principal.value=value?fmtMoney(value):'';render()});['med-age','med-retirement-age','med-life-expectancy','med-saving-plan-select','med-plan-select'].forEach(id=>document.getElementById(id).addEventListener('change',render));document.getElementById('med-adjustment-slider').addEventListener('input',event=>{document.getElementById('med-slider-val').textContent=parseFloat(event.target.value).toFixed(1)+'%';render()});document.getElementById('toggle-actual-btn').addEventListener('click',event=>{const expanded=event.currentTarget.getAttribute('aria-expanded')==='true';event.currentTarget.setAttribute('aria-expanded',String(!expanded));event.currentTarget.textContent=expanded?'顯示實繳保費與總結算':'隱藏實繳保費與總結算';document.querySelectorAll('.actual-column').forEach(cell=>cell.hidden=expanded)});document.getElementById('toggle-formula-btn').addEventListener('click',event=>{const formula=document.getElementById('formula'),expanded=event.currentTarget.getAttribute('aria-expanded')==='true';event.currentTarget.setAttribute('aria-expanded',String(!expanded));formula.hidden=expanded});render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js',{scope:'./'}).catch(console.warn)}
root.RetirementMedicalCore={VERSION,cleanNum,parseCSV,parseSavingRows,parseMedicalRows,interpolatedMultiplier,calculateMedical};if(typeof document!=='undefined')document.addEventListener('DOMContentLoaded',setup);
})(typeof window!=='undefined'?window:globalThis);
